version: "3"
services:
  itmochart:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:8000"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
